#!/bin/bash

GIT=/usr/bin/git
GITLINT=/usr/local/bin/gitlint
GITLINTCFG=$GL_ADMIN_BASE/local/hooks/gitlint.cfg
LOCAL_GITLINTCFG=.gitlint.cfg
FUNCTIONS="$GL_ADMIN_BASE/local/hooks/gitlint-functions.sh"

. $FUNCTIONS

HOOKGITLINT=$($GIT config --bool hook.gitlint)
HOOKIGNOREFEATURE=$($GIT config --bool hook.gitlint-ignore-feature-branches)

if [[ "false" == "$HOOKGITLINT" ]] || [[ -z "$HOOKGITLINT" ]]; then
   exit 0;
fi

FAIL="0"

while read OLD_REVISION NEW_REVISION REFNAME
do
    FEATUREBRANCH=$(isFeatureBranch $REFNAME)
    if [[ "true" == "$HOOKIGNOREFEATURE" ]] && [[ "true" == "$FEATUREBRANCH" ]];
    then
        continue
    fi

    validate_ref $OLD_REVISION $NEW_REVISION $REFNAME
done

if [ -n "$FAIL" ]; then
    exit $FAIL
fi

